spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
   
    password: 123456
    url: jdbc:mysql://192.168.20.6/springcloud_sell?characterEncoding=utf-8&useSSL=false

server:
  port: 8082